config/routes.rb
Munanashampurilainen::Application.routes.draw do

  root 'home#index'
  resources :incollections
  resources :inproceedings
  resources :publishers
  resources :authors
  resources :books
  resources :articles

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @Articles = Article.all
    @Books = Book.all
    @Authors = Author.all
	  @Publishers = Publisher.all
	  @References = Reference.all
	  @Inproceedings = Inproceedings.all
    @Incolletions = Incollection.all

    @AllOfThem = Article.all
    @AllOfThem << Book.all
    @AllOfThem << Inproceedings.all
    @AllOfThem << Incollection.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h4>Inproceedings</h4>

  </div>
  <table class="table">
    <tbody>
    <% @Inproceedings.each do |i| %>
        <tr>
          <td><%= link_to i.title, i  %></td>
        </tr>
    <% end %>
    <tfoot>
    <th>
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown">
          Actions <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'New inproceedings', new_inproceedings_path %></li>
          <li><%= link_to 'List all', inproceedings_index_path %></li>
        </ul>
      </div>
    </th>
    </tfoot>
    </tbody>
  </table>
</div>

<div class="panel panel-default">
  <div class="panel-heading"><h4>Incollections</h4>

  </div>
  <table class="table">
    <tbody>
    <% @Incolletions.each do |i| %>
        <tr>
          <td><%= link_to i.title, i  %></td>
        </tr>
    <% end %>
    <tfoot>
    <th>
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown">
          Actions <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'New incollections', new_incollection_path %></li>
          <li><%= link_to 'List all', incollections_path %></li>
        </ul>
      </div>
    </th>
    </tfoot>
    </tbody>
  </table>
</div>


<div class="panel panel-default">
  <div class="panel-heading"><h4>Articles</h4>

  </div>
  <table class="table">
    <tbody>
    <% @Articles.each do |i| %>
        <tr>
          <td><%= link_to i.title, i  %></td>
        </tr>
    <% end %>
    <tfoot>
    <th>
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown">
          Actions <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'New article', new_article_path %></li>
          <li><%= link_to 'List all', articles_path %></li>
        </ul>
      </div>
    </th>
    </tfoot>
    </tbody>
  </table>
</div>

<div class="panel panel-default">
  <div class="panel-heading"><h4>Books</h4>

  </div>
  <table class="table">
    <tbody>
    <% @Books.each do |i| %>
        <tr>
          <td><%= link_to i.title, i  %></td>
        </tr>
    <% end %>
    <tfoot>
    <th>
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown">
          Actions <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'New article', new_book_path %></li>
          <li><%= link_to 'List all', books_path %></li>
        </ul>
      </div>
    </th>
    </tfoot>
    </tbody>
  </table>
</div>