config/routes.rb
Munanashampurilainen::Application.routes.draw do

  root 'home#index'
  resources :incollections
  resources :inproceedings
  resources :publishers
  resources :authors
  resources :books
  resources :articles

end

app/models/inproceedings.rb
class Inproceedings < ActiveRecord::Base
  include BibtexOutput

  validates :author, :title, :booktitle, :year, presence: true
end

app/controllers/inproceedings_controller.rb
class InproceedingsController < ApplicationController
  before_action :set_inproceedings, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json, :bib

  # GET /inproceedings
  # GET /inproceedings.json
  def index
    @inproceedings = Inproceedings.all
  end

  # GET /inproceedings/1
  # GET /inproceedings/1.json
  # GET /inproceedings/1.bib
  def show
    respond_with @inproceedings
  end

  # GET /inproceedings/new
  def new
    @inproceedings = Inproceedings.new
  end

  # GET /inproceedings/1/edit
  def edit
  end

  # POST /inproceedings
  # POST /inproceedings.json
  def create
    @inproceedings = Inproceedings.new(inproceedings_params)

    respond_to do |format|
      if @inproceedings.save
        format.html { redirect_to @inproceedings, notice: 'Inproceedings was successfully created.' }
        format.json { render action: 'show', status: :created, location: @inproceedings }
      else
        format.html { render action: 'new' }
        format.json { render json: @inproceedings.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inproceedings/1
  # PATCH/PUT /inproceedings/1.json
  def update
    respond_to do |format|
      if @inproceedings.update(inproceedings_params)
        format.html { redirect_to @inproceedings, notice: 'Inproceedings was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @inproceedings.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inproceedings/1
  # DELETE /inproceedings/1.json
  def destroy
    @inproceedings.destroy
    respond_to do |format|
      format.html { redirect_to inproceedings_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inproceedings
      @inproceedings = Inproceedings.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inproceedings_params
      params.require(:inproceedings).permit(:author, :title, :booktitle, :year)
    end
end

app/helpers/inproceedings_helper.rb
module InproceedingsHelper
end

app/views/inproceedings/_form.html.erb
<%= form_for(@inproceedings) do |f| %>
  <% if @inproceedings.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inproceedings.errors.count, "error") %> prohibited this inproceedings from being saved:</h2>

      <ul>
      <% @inproceedings.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :booktitle %><br>
    <%= f.text_field :booktitle %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inproceedings/edit.html.erb
<h1>Editing inproceedings</h1>

<%= render 'form' %>

<%= link_to 'Show', @inproceedings %> |
<%= link_to 'Back', inproceedings_index_path %>

app/views/inproceedings/index.html.erb
<h1>Listing inproceedings</h1>

<table class="table">
  <thead>
    <tr>
      <th>Author</th>
      <th>Title</th>
      <th>Booktitle</th>
      <th>Year</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @inproceedings.each do |inproceedings| %>
      <tr>
        <td><%= inproceedings.author %></td>
        <td><%= inproceedings.title %></td>
        <td><%= inproceedings.booktitle %></td>
        <td><%= inproceedings.year %></td>
        <td><%= link_to 'Show', inproceedings %></td>
        <td><%= link_to 'Edit', edit_inproceedings_path(inproceedings) %></td>
        <td><%= link_to 'Destroy', inproceedings, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inproceedings', new_inproceedings_path %>

app/views/inproceedings/new.html.erb
<h1>New inproceedings</h1>

<%= render 'form' %>

<%= link_to 'Back', inproceedings_index_path %>

app/views/inproceedings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @inproceedings.author %>
</p>

<p>
  <strong>Title:</strong>
  <%= @inproceedings.title %>
</p>

<p>
  <strong>Booktitle:</strong>
  <%= @inproceedings.booktitle %>
</p>

<p>
  <strong>Year:</strong>
  <%= @inproceedings.year %>
</p>

<%= link_to 'Bib', inproceedings_path(@inproceedings)+".bib" %> |
<%= link_to 'Edit', edit_inproceedings_path(@inproceedings) %> |
<%= link_to 'Back', inproceedings_index_path %>